export interface DownloadTemplateOptions {
  bold?: (value: string) => string;
  title?: string;
  label?: string;
  icon?: string;
  loadingText?: string;
  showTitle?: boolean;
  showLoading?: boolean;
  showCost?: boolean;
  showUrl?: boolean;
  showDuration?: boolean;
  showQuality?: boolean;
  showSize?: boolean;
  showType?: boolean;
  showViews?: boolean;
  showLikes?: boolean;
  showComments?: boolean;
  showShares?: boolean;
  showAuthor?: boolean;
  showChannel?: boolean;
  showArtist?: boolean;
  showAlbum?: boolean;
  showPackage?: boolean;
  showVersion?: boolean;
  showTotal?: boolean;
  showExtension?: boolean;
  author?: string;
  channel?: string;
  artist?: string;
  album?: string;
  duration?: string;
  quality?: string;
  size?: string;
  type?: string;
  cost?: string | number;
  url?: string;
  views?: string | number;
  likes?: string | number;
  comments?: string | number;
  shares?: string | number;
  total?: string | number;
  packageName?: string;
  version?: string;
  extension?: string;
};
